name: Build and Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2

      - name: Set version from tag (Windows)
        shell: pwsh
        run: |
          $tag = $env:GITHUB_REF_NAME -replace '^v', ''
          (Get-Content Cargo.toml) -replace '^version = ".*"', "version = `"$tag`"" | Set-Content Cargo.toml
          echo "TAG=$tag" >> $env:GITHUB_ENV

      - run: cargo build --release

      - name: Rename binary (Windows)
        shell: pwsh
        run: Move-Item -Path target/release/app.exe -Destination automatize-marketplace-windows.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            automatize-marketplace-windows.exe
          if-no-files-found: ignore

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Verify downloaded artifacts
        run: ls -la artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/automatize-marketplace-windows.exe
